#pragma once

#include <noether_tpp/core/face_selection.h>
#include <noether_gui/widgets/outline_tool.h>
#include <noether_tpp/core/face_coverage.h>
#include <noether_tpp/core/types.h>
#include <noether_tpp/core/tool_path_planner_pipeline.h>
#include <noether_tpp/core/tool_path_recipe.h>
#include <Eigen/Core>
#include <QMainWindow>
#include <vtkSmartPointer.h>
#include <pcl/PolygonMesh.h>
#include <map>
#include <memory>
#include <string>
#include <vector>

class QVTKOpenGLNativeWidget;
class QDir;
class QComboBox;
class QDoubleSpinBox;
class QCheckBox;
class QLabel;
class QLayout;
class QListWidget;
class QListWidgetItem;
class QPushButton;
class vtkActor;
class vtkPolyDataMapper;
class vtkProp;
class vtkRenderer;
class vtkAxes;
class vtkAxesActor;
class vtkTubeFilter;
class vtkPropAssembly;
class vtkPolyData;
class vtkActor2D;
class vtkCellPicker;
class vtkPolyDataMapper2D;
class vtkUnsignedCharArray;

namespace Ui
{
class TPP;
}

namespace noether
{
class ConfigurableTPPPipelineWidget;
class PathEditWidget;
class WidgetFactory;

enum class LineStyle
{
  INTRA_SEGMENT = 0, /*@brief between waypoints in a segment*/
  INTER_SEGMENT,     /*@brief between tool path segments*/
  INTER_PATH,        /*@brief between tool paths*/
};

/**
 * @brief Selection tool the left mouse button drives in the 3D view.
 */
enum class SelectionTool
{
  /** @brief Click a face, grow a region across edges flatter than the flatness angle */
  Region,
  /** @brief Drag to paint the faces within the brush radius, measured along the surface */
  Brush,
  /**
   * @brief Click to place the vertices of an outline, close it on its first vertex, with Enter or
   * a double-click; the camera-facing faces inside are selected
   */
  Polygon,
  /** @brief Drag to erase the work selection within the brush radius */
  Eraser
};

/**
 * @brief Basic tool path planning widget
 * @details Allows the user to laod a mesh from file, configure a tool path planning pipeline, and generate tool paths
 * from the input mesh
 */
class TPPWidget : public QMainWindow
{
public:
  TPPWidget(std::shared_ptr<const WidgetFactory> factory, QWidget* parent = nullptr);

  /**
   * @brief Sets the file path for the mesh to use for tool path planning
   */
  void setMeshFile(const QString& file);

  /**
   * @brief Configures the GUI tool path planning pipeline from a YAML configuration file
   */
  void configure(const QString& file);

  /**
   * @brief Clears all interactively selected regions
   */
  void clearSelection();

  /**
   * @brief Invokes the planning of a tool path based on the current mesh file and tool path planner configuration
   * @details A tool path is planned for each region the user has selected in the viewer (see
   * ::onCellClicked). Each selected region is extracted as a submesh and run through the pipeline's
   * mesh modifier, planner, and tool path modifier.
   */
  void plan();

  /**
   * @brief Saves the modified meshes created during the planning of a tool path to a directory
   */
  void saveModifiedMeshes(const QDir& save_dir);

  /**
   * @brief Get the planned tool paths
   * @details The highest level vector represents the tool paths generated for each mesh "fragment" generated by the
   * mesh modifier in the tool path planning pipeline
   */
  std::vector<ToolPaths> getToolPaths() const { return tool_paths_; }

  /**
   * @brief Charge un chemin d'outil deja enregistre pour le retoucher
   * @details Les passes du fichier prennent la place d'une generation : le dock Trajectoire les
   * recoit telles quelles, approche et retrait compris, et tout ce qu'il permet s'applique
   * (ordre, suppression, deplacement de points). Save tool paths reecrit le resultat.
   * @param file Fichier YAML ecrit par Save tool paths, ou par la cellule
   * @throws std::runtime_error si le fichier ne se lit pas comme un chemin d'outil
   */
  void loadToolPaths(const QString& file);

  /**
   * @brief Saves the tool paths to a YAML file, and the retouching recipe beside it
   * @details What is written is the *retouched* path, the one the Trajectory dock shows. The
   * recipe that turns the generation into it is written to a sibling file, so the delivered path
   * stays a derived artefact rather than a hand edit nobody can replay. See ::editsFileName.
   * @param file Destination of the tool path
   */
  void saveToolPaths(const QString& file);

  /**
   * @brief Name of the recipe file that belongs beside a tool path file
   * @details `<stem>.edits.yaml`, so the pairing survives whatever name the operator saves under.
   * @param tool_path_file Destination of the tool path
   */
  static QString editsFileName(const QString& tool_path_file);

  // Visibility controls
  void showOriginalMesh(const bool);
  void showModifiedMesh(const bool);
  void showUnmodifiedToolPath(const bool);
  void showUnmodifiedConnectedPath(const bool);
  void showModifiedToolPath(const bool);
  void showModifiedConnectedPath(const bool);
  void showAxes(const bool);

protected:
  void onLoadMesh(const bool /*checked*/);
  void onClearSelection(const bool /*checked*/);
  void onSaveModifiedMeshes(const bool /*checked*/);
  void onSaveToolPaths(const bool /*checked*/);
  /** @brief Bouton « Charger un chemin » : choisit le fichier puis appelle ::loadToolPaths */
  void onLoadToolPaths();
  /**
   * @brief Tells the operator what forbids delivering the retouching, if anything does
   * @details Also covers the absence of any planning at all, the Trajectory dock being the only
   * thing that carries a generation seen through to the end and the recipe the check reads.
   * @return True when the retouching may be written out
   */
  bool reportRetouchFaults();
  /** @brief Writes the retouching recipe beside the tool path file just written */
  void savePathEdits(const QString& tool_path_file);
  void render();

  /**
   * @brief The passes the Trajectory dock delivers, nested as the file format expects
   * @details Falls back to the generation itself while no planning has run.
   */
  std::vector<ToolPaths> editedToolPaths() const;
  /** @brief Redraws the retouched path and its highlight after an edit in the Trajectory dock */
  void onPathEdited();
  /** @brief Redraws the outline that marks the pass selected in the Trajectory dock */
  void updatePathHighlight();
  /**
   * @brief Asks before a new planning throws away the retouching in the Trajectory dock
   * @return True when planning may go ahead
   */
  bool confirmDiscardPathEdits();
  /** @brief Drops the planning and its retouching, and takes their actors off the viewer */
  void clearPlannedPaths();
  /** @brief Builds the Trajectory dock and wires it to the viewer; called once from the constructor */
  void buildPathEditDock();

  /** @brief Builds the VTK poly data, face adjacency, per-cell color array, and resets the selection */
  void buildSelectionData();
  /** @brief Handles a viewer click on the mesh: grows/toggles the region containing the clicked face */
  void onCellClicked(int cell_id);
  /**
   * @brief Grows a continuous, roughly-flat region of faces starting from a seed face
   * @details Flood-fills across edge-adjacent faces while the angle between a face and its neighbor
   * stays within the flatness-angle threshold, so growth follows a gently curving surface and stops
   * at sharper edges.
   */
  std::vector<int> growRegion(int seed_face) const;
  /** @brief Refreshes the per-cell colors from the current selection (white = unselected) */
  void updateSelectionColors();
  /**
   * @brief Returns, per face, whether it survives erosion by the tool radius
   * @details A face is kept only if it belongs to a selected region and its geodesic distance to
   * that region's boundary is at least the tool radius. This removes the frange of width = tool
   * radius around each region (where a disc tool would overhang onto neighbors), so a strip
   * narrower than the tool diameter is eroded away entirely.
   */
  std::vector<char> erodeSelection() const;

  /** @brief Picks the mesh face under a display position; -1 when the ray misses the mesh */
  int pickFace(int x, int y) const;
  /**
   * @brief Face et point du maillage sous une position d'affichage
   * @param point Sortie : le point touche, sur la face
   * @return La face touchee, -1 quand le rayon rate le maillage
   */
  int pickPoint(int x, int y, Eigen::Vector3d& point) const;
  /**
   * @brief Point 3D sous une position d'affichage, quel que soit l'acteur touche
   * @details Un point du chemin est dessine par-dessus le maillage : le clic qui le vise touche
   * la fleche, pas la face. Pour saisir, la position touchee suffit.
   * @return Vrai quand le rayon touche quelque chose
   */
  bool pickAnyPoint(int x, int y, Eigen::Vector3d& point) const;
  /**
   * @brief Paints or erases one brush dab centred on a display position
   * @details Commits into the selection without refreshing the view: the caller refreshes once per
   * mouse event rather than once per dab.
   */
  void paintBrushDab(int x, int y, bool erase);
  /**
   * @brief Paints from the previous drag position to the given one
   * @details A move event can jump tens of pixels, which would leave a dotted trail if each event
   * painted a single dab.
   */
  void paintBrushAlongSegment(int x, int y, bool erase);

  /**
   * @brief Refuses a work selection that is not exactly one continuous patch, saying why
   * @param piece_count Number of disconnected pieces the work selection is made of
   * @return True when the selection may become one surface
   */
  bool checkPendingIsOneSurface(std::size_t piece_count);
  /** @brief Validates the work selection as one surface and appends it to the list */
  void onAddSurface();
  /** @brief Removes the surface selected in the list and frees its faces */
  void onRemoveSurface();

  /** @brief Rewrites a surface's list entry: its rank, its face count and its trace */
  void relabelSurface(QListWidgetItem* item) const;
  /** @brief Vrai quand le bouton « Trace manuel » de l'onglet Traitement est enfonce */
  bool tracing() const;
  /** @brief Onglet Traitement : le trace manuel, son pas et ses corrections */
  void buildTreatmentDock();
  /** @brief Contenu de l'onglet Traitement */
  QWidget* buildTreatmentPanel();
  /** @brief Le bouton Trace manuel change d'etat : il prend ou rend le tirage de la vue */
  void onTraceToggled(bool checked);
  /** @brief Le bouton Deplacer des points change d'etat : il prend ou rend le tirage de la vue */
  void onMovePointsToggled(bool checked);
  /**
   * @brief Genere chaque surface tracee, dans l'ordre des surfaces
   * @param unmodified Sortie : chemins bruts de la generation
   * @return Les surfaces sans trace, qui n'ont rien produit
   */
  std::vector<int> planTracedSurfaces(std::vector<ToolPaths>& unmodified);
  /** @brief Met les fragments et les chemins dans la vue, et les passes dans le dock Trajectoire */
  void showPlannedPaths(const std::vector<ToolPaths>& unmodified);
  /** @brief Dit a l'operateur quelles surfaces n'ont pas ete generees, faute de trace */
  void reportUntracedSurfaces(const std::vector<int>& untraced);


  /** @brief Identifiant de la surface selectionnee dans la liste, -1 sans selection */
  int selectedSurfaceId() const;
  /** @brief Debut d'un tirage du trace : fixe le depart si le trace est vide, sinon amorce un segment */
  void onTraceDragStart(int x, int y);
  /** @brief Suite du tirage : deplace la fin provisoire du segment sur la surface */
  void onTraceDragMove(int x, int y);
  /** @brief Fin du tirage : le segment provisoire devient un sommet du trace */
  void onTraceDragEnd();
  /** @brief Touches du trace : Retour arriere retire le dernier sommet, Echap efface le trace */
  void onTraceKey(const std::string& key);
  /** @brief Sommets du trace de la surface selectionnee, suivis de la fin provisoire du tirage en cours */
  std::vector<Eigen::Vector3d> traceVerticesWithPreview(int surface_id) const;
  /**
   * @brief Points du trace de la surface selectionnee, tirage en cours compris, ramenes sur la surface
   * @param normals Sortie : normale de la face sous chaque point
   */
  std::vector<Eigen::Vector3d> projectedTraceSamples(int surface_id, std::vector<Eigen::Vector3d>& normals) const;
  /** @brief Redessine les points, les lignes et les cercles du disque du trace de la surface selectionnee */
  void updateTraceMarkers();
  /** @brief Cercles du disque autour de points poses a plat sur la surface, dans le plan de chaque normale */
  vtkSmartPointer<vtkPolyData> flatDiscCircles(const std::vector<Eigen::Vector3d>& points,
                                               const std::vector<Eigen::Vector3d>& normals) const;

  /** @brief Vrai quand le bouton « Deplacer des points » est enfonce : le tirage saisit une pose */
  bool movingPoints() const;
  /** @brief Debut d'un tirage en mode deplacement : saisit la pose de contact la plus proche du clic */
  void onPointDragStart(int x, int y);
  /**
   * @brief Pose de contact la plus proche d'un point, dans la generation deplacee
   * @details Les poses d'approche et de retrait (kSkirtPoses a chaque bout) ne se saisissent pas :
   * elles suivent la pose de contact voisine, voir ::moveSkirtPoses.
   * @return Vrai quand une pose de contact est a moins de kGrabToleranceM
   */
  bool locateContactPose(const Eigen::Vector3d& clicked, PoseMove& found) const;
  /**
   * @brief Fait suivre l'approche ou le retrait a la pose de contact qui vient d'etre posee
   * @details Si la pose deplacee est la premiere de contact, l'approche garde, dans le repere de
   * cette pose, la place qu'elle avait : meme hauteur, meme axe. Idem pour le retrait derriere la
   * derniere pose de contact.
   */
  void moveSkirtPoses();
  /** @brief Suite du tirage : la pose saisie suit le curseur sur le maillage, z le long de la face */
  void onPointDragMove(int x, int y);
  /** @brief Fin du tirage : la pose deplacee entre dans la retouche, le chemin est reconstruit une fois */
  void onPointDragEnd();
  /**
   * @brief Bouton « Valider la nouvelle disposition » : sort du mode deplacement et confirme
   * @details Les poses deplacees font deja partie du chemin livre, donc du fichier ecrit par
   * Save tool paths ; le bouton rend cette prise en compte explicite et rend le tirage aux outils.
   */
  void validateLayout();
  /**
   * @brief Redessine la marque de la pose saisie et son cercle
   * @details Pendant le tirage, seuls ces deux acteurs bougent : reconstruire le chemin, la
   * couverture et tous les cercles a chaque mouvement de souris rendrait le geste saccade.
   */
  void updateGrabMarker();
  /**
   * @brief Dessine un cercle de rayon outil autour de chaque point de contact du chemin livre
   * @details Le cercle est dans le plan de la pose : c'est l'empreinte du disque pose la. Il
   * montre d'un coup d'oeil un point trop pres d'un bord ou d'un relief. Rien n'est calcule
   * contre la piece, c'est une aide visuelle. Efface sans chemin, sans rayon, ou case decochee.
   */
  void updateDiscCircles();
  /**
   * @brief Ramene des points sur une surface : chacun sur le point le plus proche de ses faces
   * @details Les points d'un trace sont poses sur la corde entre deux sommets ; sur une surface
   * courbe la corde passe dessous. Le point projete et la normale de la face touchee donnent la
   * pose reelle de l'outil.
   * @param points Entree : points a projeter ; sortie : leurs projetes
   * @param normals Sortie : normale de la face portant chaque projete
   */
  void projectOnSurface(int surface_id, std::vector<Eigen::Vector3d>& points, std::vector<Eigen::Vector3d>& normals) const;
  /** @brief Mention du trace manuel dans l'entree de liste d'une surface, vide sans trace */
  QString describeTrace(int surface_id) const;
  /** @brief Vrai quand la surface porte un trace manuel d'au moins deux sommets */
  bool surfaceHasTrace(int surface_id) const;
  /**
   * @brief Planifie une surface tracee a la main : le trace, une approche devant, un retrait derriere
   * @details Aucun parametre de Noether n'est lu : ni planificateur, ni modificateurs de chemin.
   * L'approche et le retrait sont poses a la hauteur de l'onglet Traitement. Ajoute le fragment,
   * le chemin brut et le chemin livre aux listes de la generation en cours.
   * @param faces Faces de la surface, pour le fragment affiche
   * @param unmodified Sortie : chemins bruts de la generation en cours
   */
  void planTracedSurface(int surface_id, const std::vector<int>& faces, std::vector<ToolPaths>& unmodified);
  /** @brief Le trace manuel d'une surface, echantillonne au pas choisi, en un seul segment de poses */
  ToolPaths tracedToolPaths(int surface_id) const;

  /** @brief Adds or removes faces of the work selection; faces owned by a surface are skipped */
  void paintPending(const std::vector<int>& faces, bool erase);
  /** @brief Connected components of the work selection, over the face adjacency */
  std::vector<std::vector<int>> pendingComponents() const;

  /** @brief Camera-facing faces whose centroid projects inside the outline being traced */
  std::vector<int> facesInsideOutline() const;
  /** @brief A click of the polygon tool: adds a vertex, or closes the outline when it lands on the first one */
  void onOutlineClick(int x, int y, bool erase, bool double_click);
  /** @brief Keys of the polygon tool: Enter closes, Backspace removes the last vertex, Escape clears */
  void onKeyPressed(const std::string& key, bool shift);
  /** @brief Commits the faces inside the outline and clears it */
  void closeOutline(bool erase);
  /** @brief Rebuilds the 2D outline overlay from the outline vertices, hiding it when too short */
  void updateOutlineOverlay();
  /** @brief Enables the reading that governs the active tool and greys out the others */
  void updateToolControls();

  /** @brief Start of a drag consumed by the active selection tool; `erase` reports the Shift key */
  void onDragStart(int x, int y, bool erase);
  /** @brief Continuation of a consumed drag */
  void onDragMove(int x, int y, bool erase);
  /** @brief End of a consumed drag */
  void onDragEnd(bool erase);

  std::string mesh_file_;

  Ui::TPP* ui_;
  ConfigurableTPPPipelineWidget* pipeline_widget_;

  // Viewer rendering
  QVTKOpenGLNativeWidget* render_widget_;
  vtkSmartPointer<vtkRenderer> renderer_;
  vtkSmartPointer<vtkPolyDataMapper> mesh_mapper_;
  vtkSmartPointer<vtkActor> mesh_actor_;

  vtkSmartPointer<vtkPropAssembly> tool_path_actor_;
  vtkSmartPointer<vtkPropAssembly> connected_path_actor_;
  vtkSmartPointer<vtkPropAssembly> unmodified_tool_path_actor_;
  vtkSmartPointer<vtkPropAssembly> unmodified_connected_path_actor_;
  vtkSmartPointer<vtkPropAssembly> mesh_fragment_actor_;
  /** @brief Outline drawn over the pass selected in the Trajectory dock */
  vtkSmartPointer<vtkPropAssembly> highlight_actor_;

  vtkSmartPointer<vtkAxes> axes_;
  vtkSmartPointer<vtkAxesActor> axes_actor_;
  vtkSmartPointer<vtkTubeFilter> tube_filter_;

  std::vector<ToolPaths> tool_paths_;

  // Interactive region selection
  /** @brief The full input mesh currently loaded (selection canvas) */
  pcl::PolygonMesh mesh_;
  /** @brief VTK representation of mesh_ used for display and cell picking (cell i == polygon i) */
  vtkSmartPointer<vtkPolyData> selection_poly_;
  /** @brief Per-cell RGB colors of selection_poly_ (white = unselected, colored = selected) */
  vtkSmartPointer<vtkUnsignedCharArray> cell_colors_;
  /** @brief Picker mapping a viewer click to a mesh face (cell) */
  vtkSmartPointer<vtkCellPicker> cell_picker_;
  /** @brief For each face, indices of its edge-adjacent faces */
  FaceAdjacency face_adjacency_;
  /** @brief Unit normal of each face (parallel to mesh_.polygons) */
  std::vector<Eigen::Vector3d> face_normals_;
  /** @brief Centroid of each face (parallel to mesh_.polygons), for geodesic distances */
  std::vector<Eigen::Vector3d> face_centroids_;
  /** @brief For each face, the id of the added surface it belongs to, or -1 if free */
  std::vector<int> face_region_;
  /** @brief Work selection being built by the tools; faces here are not yet part of any surface */
  std::vector<char> pending_faces_;
  /** @brief Monotonically increasing id assigned to each newly selected region (for coloring) */
  int next_region_id_ = 0;

  /** @brief Tool the left mouse button drives in the 3D view */
  SelectionTool tool_ = SelectionTool::Region;
  /** @brief Display position of the last drag event, to paint the gap up to the next one */
  Eigen::Vector2d drag_position_ = Eigen::Vector2d::Zero();
  /** @brief Outline being traced by the polygon tool, in display coordinates */
  OutlineBuilder outline_;
  /** @brief Closed polyline of the outline being traced, in display coordinates */
  vtkSmartPointer<vtkPolyData> outline_poly_;
  vtkSmartPointer<vtkPolyDataMapper2D> outline_mapper_;
  vtkSmartPointer<vtkActor2D> outline_actor_;

  /** @brief Toolbar selector for the active selection tool */
  QComboBox* tool_combo_box_ = nullptr;
  /** @brief Spin box controlling the flatness (max angle between adjacent faces, in degrees) */
  QDoubleSpinBox* flatness_angle_spin_box_ = nullptr;
  /** @brief Spin box controlling the brush diameter (mm), measured along the surface */
  QDoubleSpinBox* brush_diameter_spin_box_ = nullptr;
  /** @brief Spin box controlling the tool radius (mm) used to erode the selected regions */
  QDoubleSpinBox* tool_radius_spin_box_ = nullptr;
  /** @brief Check box enabling/disabling the tool-radius erosion */
  QCheckBox* tool_radius_enabled_check_box_ = nullptr;
  /** @brief One entry per added surface; the item data carries the surface id */
  QListWidget* surface_list_ = nullptr;
  /** @brief Toolbar button validating the work selection into the list */
  QPushButton* add_surface_button_ = nullptr;
  /** @brief Button under the list removing the selected surface */
  QPushButton* remove_surface_button_ = nullptr;
  /** @brief Sommets du trace manuel par surface, dans l'ordre de parcours */
  std::map<int, std::vector<Eigen::Vector3d>> surface_traces_;
  /** @brief Vrai pendant un tirage du trace : trace_preview_end_ vaut alors quelque chose */
  bool trace_preview_active_ = false;
  /** @brief Fin provisoire du segment en cours de tirage, sur la surface */
  Eigen::Vector3d trace_preview_end_ = Eigen::Vector3d::Zero();
  /** @brief Espacement des points du trace manuel, en millimetres */
  QDoubleSpinBox* trace_step_spin_box_ = nullptr;
  /** @brief Bouton a bascule de l'onglet Traitement : le tirage trace sur la surface selectionnee */
  QPushButton* trace_button_ = nullptr;
  /** @brief Hauteur de l'approche et du retrait au-dessus du premier et du dernier point, en millimetres */
  QDoubleSpinBox* approach_height_spin_box_ = nullptr;
  /** @brief Points du trace manuel dans la vue */
  vtkSmartPointer<vtkActor> trace_actor_;
  /** @brief Lignes du trace manuel, de point en point */
  vtkSmartPointer<vtkActor> trace_line_actor_;
  /** @brief Cercles du disque autour des points du chemin livre */
  vtkSmartPointer<vtkActor> disc_actor_;
  /** @brief Cercles du disque le long du trace en cours */
  vtkSmartPointer<vtkActor> trace_disc_actor_;
  /** @brief Bouton a bascule du dock Trajectoire : le tirage deplace des poses du chemin livre */
  QPushButton* move_points_button_ = nullptr;
  /** @brief Pose de la generation saisie par le tirage en cours */
  PoseMove grabbed_;
  /** @brief Vrai pendant un tirage qui deplace une pose */
  bool grab_active_ = false;
  /** @brief Position de la pose saisie avant le tirage : son cercle cyan est cache pendant qu'elle bouge */
  Eigen::Vector3d grab_origin_ = Eigen::Vector3d::Zero();
  /** @brief Passe de la generation deplacee telle qu'elle etait a la saisie, pour y lire l'approche et le retrait */
  ToolPathSegment grab_segment_before_;
  /** @brief Bouton du dock Trajectoire qui clot le deplacement de points et confirme la disposition */
  QPushButton* validate_layout_button_ = nullptr;
  /** @brief Bouton du dock Trajectoire qui charge un chemin deja enregistre */
  QPushButton* load_tool_paths_button_ = nullptr;
  /** @brief Marque de la pose saisie */
  vtkSmartPointer<vtkActor> grab_actor_;
  /** @brief Cercle du disque de la pose saisie, qui suit le tirage */
  vtkSmartPointer<vtkActor> grab_disc_actor_;
  /** @brief Panel where the operator retouches the planned path */
  PathEditWidget* path_edit_ = nullptr;
  /** @brief The submeshes planned in the last plan() call (one per selected region), for display/save */
  std::vector<pcl::PolygonMesh> fragments_;
};

}  // namespace noether
